#elasticsearch:
#  host: 127.0.0.1
#  port: 9200
spring:
  elasticsearch:
    rest:
      username: elastic
      password: changeme
      uris: http://localhost:9200
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: user
#    password: pass
#    hikari:
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#        useLocalSessionState: true
#        rewriteBatchedStatements: true
#        cacheResultSetMetadata: true
#        cacheServerConfiguration: true
#        elideSetAutoCommits: true
#        maintainTimeStats: false
#      maximum-pool-size: 30
#      minimum-idle: 5
#      pool-name: SpringBootJPAHikariCP
#      idle-timeout: 600000
#      max-lifetime: 25000
#      connection-timeout: 30000
#    #    initialization-mode: always
#  jpa:
#    # API 호출시, SQL 문을 콘솔에 출력한다.
#    show-sql: true
#
#    # DDL 정의시 데이터베이스의 고유 기능을 사용합니다.
#    # ex) 테이블 생성, 삭제 등
#    spring.jpa.generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate.ddl-auto: update # spring.jpa.properties.hibernate.hbm2ddl.auto 속성과 와 동일
#  output:
#    ansi:
#      enabled: always
